# Generated by Django 4.2.7 on 2023-12-04 23:34

from django.db import migrations, models
import server.models
import server.validators


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_category_icon_alter_server_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_banner_upload_path),
        ),
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_icon_upload_path, validators=[server.validators.validate_icon_image_size, server.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=server.models.category_icon_upload_path, validators=[server.validators.validate_icon_image_size, server.validators.validate_image_file_extension]),
        ),
    ]
