# Generated by Django 4.2.7 on 2023-12-19 19:43

from django.db import migrations, models
import server.models
import server.validators


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_server_banner_server_icon_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=server.models.category_icon_upload_path),
        ),
        migrations.AlterField(
            model_name='channel',
            name='topic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='server',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_banner_upload_path, validators=[server.validators.validate_image_file_extension]),
        ),
    ]
